-- Listings Table Migration
-- Run this SQL in your Supabase SQL Editor
-- Creates the listings table with RLS policies
-- Safe to re-run (uses IF NOT EXISTS)

-- First, ensure profiles table has is_verified and role columns (if they don't exist)
ALTER TABLE profiles 
  ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS role TEXT DEFAULT 'user';

-- Create indexes on these columns for better RLS policy performance
CREATE INDEX IF NOT EXISTS profiles_is_verified_idx ON profiles(is_verified) WHERE is_verified = true;
CREATE INDEX IF NOT EXISTS profiles_role_idx ON profiles(role) WHERE role = 'admin';

-- Create listings table
CREATE TABLE IF NOT EXISTS listings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC,
  city TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE listings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for listings

-- SELECT: Any authenticated user can read all listings
CREATE POLICY "Authenticated users can view all listings"
  ON listings FOR SELECT
  TO authenticated
  USING (true);

-- INSERT: Only verified users (is_verified = true) OR admins (role = 'admin') can create listings
CREATE POLICY "Verified users and admins can create listings"
  ON listings FOR INSERT
  TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND (profiles.is_verified = true OR profiles.role = 'admin')
    )
    AND auth.uid() = user_id
  );

-- UPDATE: Only owner (user_id = auth.uid()) OR admin can update
CREATE POLICY "Owners and admins can update listings"
  ON listings FOR UPDATE
  TO authenticated
  USING (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  )
  WITH CHECK (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- DELETE: Only owner OR admin can delete
CREATE POLICY "Owners and admins can delete listings"
  ON listings FOR DELETE
  TO authenticated
  USING (
    user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM profiles
      WHERE profiles.id = auth.uid()
      AND profiles.role = 'admin'
    )
  );

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS listings_user_id_idx ON listings(user_id);
CREATE INDEX IF NOT EXISTS listings_created_at_idx ON listings(created_at DESC);
CREATE INDEX IF NOT EXISTS listings_city_idx ON listings(city);
CREATE INDEX IF NOT EXISTS listings_price_idx ON listings(price);

-- Function to auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_listings_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at on UPDATE
DROP TRIGGER IF EXISTS update_listings_updated_at ON listings;
CREATE TRIGGER update_listings_updated_at
  BEFORE UPDATE ON listings
  FOR EACH ROW
  EXECUTE FUNCTION update_listings_updated_at();
